name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
    branches:
    - master

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Build a binary wheel and a source tarball
        run: |
          make build-dist
      - name: Check version for publishing on PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          python check_version.py
          echo "Publishing !!!!!"
      - name: Publish distribution 📦 to PyPI
        if: ${{ success() && startsWith(github.event.ref, 'refs/tags') }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}